import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar1 from "./component/navbar1";
import Topsale from "./component/navbar1 copy";
import Footer from "./component/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
        <body>
          {/* Hide Topsale on mobile */}
          <div className="hidden lg:block">
            <Topsale />
          </div>
          <Navbar1 />
          {children}
          <Footer />
        </body>
      </html>
   
  );
}
